modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/badasintended/wthit/issues"
displayURL = "https://github.com/badasintended/wthit"
license = "CC-BY-NC-SA-4.0"

[[mixins]]
config = "wthit.mixins.json"

[[mods]]
modId = "wthit"
version = "${version}"
displayName = "wthit"
description = "What the hell is that? Forge Edition"
authors = "deirn, TehNut, ProfMobius"
logoFile = "wthit.jpg"

[[mods]]
modId = "waila"
version = "${version}"
displayName = "waila"
description = "Actually WTHIT but with \"waila\" as it's id lmao"
authors = "deirn, TehNut, ProfMobius"
logoFile = "wthit.jpg"

[[dependencies.wthit]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wthit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wthit]]
modId = "badpackets"
mandatory = true
versionRange = "[0.5.4,)"
ordering = "NONE"
side = "BOTH"
