modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/badasintended/wthit/issues"
displayURL = "https://github.com/badasintended/wthit"
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "wthit"
version = "${version}"
displayName = "wthit"
description = "What the hell is that? Forge Edition"
authors = "deirn, TehNut, ProfMobius"
logoFile = "wthit.jpg"

[[mods]]
modId = "waila"
version = "${version}"
displayName = "waila"
description = "Actually WTHIT but with \"waila\" as it's id lmao"
authors = "deirn, TehNut, ProfMobius"
logoFile = "wthit.jpg"

[[dependencies.wthit]]
modId = "forge"
mandatory = true
versionRange = "[41.0.94,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wthit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wthit]]
modId = "badpackets"
mandatory = true
versionRange = "[0.1.2,)"
ordering = "NONE"
side = "BOTH"
